### PR TITLE
Update translation README.adoc

### PR DESCRIPTION
**Pull request by tanoueakira**
Translated some sentences.

### CODE REVIEW

**Comment by smellai** [comment]
@tanoueakira you can merge your PRs yourself :+1:

**Comment by smellai** [comment]
https://github.com/arduino/reference-en/blob/master/README.adoc please refer to english file, we are not using Manutius anymore

**Comment by tanoueakira** [comment]
Can you please tell me how to merge my pull request by myself? (I'm using web ver. GitHub)
It says 'Only those with write access to this repository can merge pull requests.'

Or Do I need to use the software version?

Thanks.

screen shot 2018-01-11 at 17 27 30

**Comment by smellai** [comment]
you should have received an invite email, haven't you?

**Comment by tanoueakira** [comment]
@smellai I checked now but I haven’t received the email.

My email address is akira.f18210@gmail.com

**Comment by mastrolinux** [comment]
Try this: https://github.com/arduino/reference-jp/invitations

**Comment by tanoueakira** [comment]
Thank you very much!

I was able to merge.

**Pull request merged**
